// API CALLS
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

// SIGN UP
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

// SIGN IN
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";
export const EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED";

// SIGN OUT
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_ERROR = "SIGNOUT_ERROR";

// RESET PASSWORD
export const RESET_SUCCESS = "RESET_SUCCESS";
export const RESET_ERROR = "RESET_ERROR";

// ARTICLES
export const LOADING = "LOADING";
export const ADD_ARTICLE = "ADD_ARTICLE";
export const EDIT_ARTICLE = "EDIT_ARTICLE";
export const GET_ARTICLES = "GET_ARTICLES";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const SET_SEARCH_BY_STRING = "SET_SEARCH_BY_STRING";
export const SET_SEARCH_BY_TAG = "SET_SEARCH_BY_TAG";
export const CLEAR_SEARCH = "CLEAR_SEARCH";
